name: mvn private deploy

on:
  push:
    branches-ignore:
      - master

jobs:
  build:
    name: build and deploy maven library to private
    runs-on: ubuntu-latest

    steps:

      - name: Deploying GitHub Actions Lib
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: maven-settings-xml-action
        uses: whelk-io/maven-settings-xml-action@4637f7c31534ec06928b10da807735657a921266
        with:
          servers: '[ {"id": "ossrh", "username": "${{secrets.CENTRAL_WRITE_PACKAGES_USER}}", "password": "${{secrets.CENTRAL_WRITE_PACKAGES_TOKEN}}" }, { "id": "github", "username": "${{secrets.PRIVATE_WRITE_PACKAGES_USER}}", "password": "${{secrets.PRIVATE_WRITE_PACKAGES_TOKEN}}" }, { "id": "github-snapshot", "username": "${{secrets.PRIVATE_WRITE_PACKAGES_USER}}", "password": "${{secrets.PRIVATE_WRITE_PACKAGES_TOKEN}}" }, { "id": "github-release", "username": "${{secrets.PRIVATE_WRITE_PACKAGES_USER}}", "password": "${{secrets.PRIVATE_WRITE_PACKAGES_TOKEN}}" }, { "id": "central-release", "username": "${{secrets.CENTRAL_WRITE_PACKAGES_USER}}", "password": "${{secrets.CENTRAL_WRITE_PACKAGES_TOKEN}}" }]'

      - name: print metadata
        run: echo ${{github.ref}}

      - name: Set release version (dev)
        if: github.ref == 'refs/heads/develop'
        run: |
          sed -i "s/-SNAPSHOT<\/version>/<\/version>/1" pom.xml

      - name: Set release version (master)
        if: github.ref == 'refs/heads/master'
        run: |
          sed -i "s/-SNAPSHOT<\/version>/<\/version>/1" pom.xml

      - name: Set snapshot version
        if: github.ref != 'refs/heads/master'
        run: |
          build_date=`date -u +"%Y%m%d%H%M%S"`
          branch_name=`echo ${GITHUB_REF##*\/} | sed 's/^.*\/\([^\/]*\)$/\1/' | sed "s/[^[:alnum:]-]//g"`
          sed -i "s/-SNAPSHOT<\/version>/-$build_date-$branch_name<\/version>/1" pom.xml

      - name: Set distribution repo
        if: github.ref != 'refs/heads/master'
        run: |
          find_token='<distributionManagement\/>'
          dist_repo='<distributionManagement><repository><id>github-snapshot<\/id><name>GitHub piplcom snapshot<\/name><url>https:\/\/maven.pkg.github.com\/piplcom\/maven-packages\/<\/url><uniqueVersion>true<\/uniqueVersion><\/repository><\/distributionManagement>'
          sed -i "s/$find_token/$dist_repo/1" pom.xml

      - name: Maven build and deploy
        run: |
          sudo apt install gnupg
          echo ${{secrets.GPG_SECRET}} | base64 -d | gpg --import --no-tty --batch --yes
          mvn deploy -Dmaven.test.skip=true -Dgpg.passphrase=${{secrets.GPG_PASSPHRASE}} -Dgpg.executable=gpg
